language: go

notifications:
  email:
    on_success: never

env:
  - GO111MODULE=on
script:
  - go build

before_deploy:
  - GOOS=linux GOARCH=amd64 go build -o ancestorquotes-linux-amd64
  - GOOS=windows GOARCH=amd64 go build -o ancestorquotes-windows-amd64.exe
  - GOOS=darwin GOARCH=amd64 go build -o ancestorquotes-macos-amd64

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
   secure: npn/SQm9Tt40nAHucoyJTYKaS4iLpKIRzxmKHuUsYtpxm0RyvMcjyMN4tG4a5vHqN8Z1QNr6WcDfOLynIFqR38yeQte3vynpWagrGuMfjkSnf2ZiyulOmUdWq/UWNj8cElW3Hzd13ocJ1/mXKv86bODeXmr1HVaiBzJL2VgJb/D41ObKrzVBJI2F74QGxBZKP3IF77Ku0VuTTg7BxfkieRujAh3L/ZYZ0E9LAcL0cHOHzxngKwzMnaHNwZ3CId94slkuQx3NhScfb2QyLvxd4xSRaLaTKgrfs1J1FQWEchk4w9HnMzRXoLFKYe+ppUFDDFkVSGHOmRuWTEJp1HFkZ+yJHpXpbZLOGFxyUxEIBuNdryboxYS53F1cFkRa215oZmBdUZ8Q2bFgkkWi+DYfXbdqEDSBB4HiBl14XoDM9wEk1balfNSdok/YmEvci9RJq3UOlMQ5nMbLI14qZut+AjCDDHao/k9/waxKapfCvMuKB3nZCh+WpLX/8JRJuxFH5DO1bsooH4D1lOdQCSSotnaNNOCbiXQ2bSE3k5dEAns/GcHGXd+er8qA51YUT0632Bj4qW22ImREt2qmHpaCtXohFdedGzhIY0DHwHhc52519B6YPQXYKO4d5g+hpVk9Bv/+Fr4va8CA/3W5y/oUtt+RuJJU9cBZWDGl+361IbY=
  file:
    - "ancestorquotes-linux-amd64"
    - "ancestorquotes-windows-amd64.exe"
    - "ancestorquotes-macos-amd64"
  on:
    tags: true